//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ataskaita
    {
        public int NUO { get; set; }
        public int IKI { get; set; }
        public int viso { get; set; }
        public int SkaitytojoId { get; set; }
        public int UzsakymoId { get; set; }
        public string Pavarde { get; set; }
        public string Vardas { get; set; }
        public string paimta { get; set; }
        public string grazinti { get; set; }
        public string knygu_suma { get; set; }
        public Nullable<int> knygu_count { get; set; }
        public string zurnalu_suma { get; set; }
        public Nullable<int> zurnalu_count { get; set; }
        public string audio_suma { get; set; }
        public Nullable<int> audio_count { get; set; }
        public Nullable<int> leidiniai { get; set; }
    }
}
