//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioKnygo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AudioKnygo()
        {
            this.UzsakymaiAudioKnygos = new HashSet<UzsakymaiAudioKnygo>();
        }
    
        public int Id { get; set; }
        public string Pav { get; set; }
        public int Trukme { get; set; }
        public string Skirsnis { get; set; }
        public int Metai { get; set; }
        public Nullable<int> IgarsintojasId { get; set; }
    
        public virtual Igarsintojai Igarsintojai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzsakymaiAudioKnygo> UzsakymaiAudioKnygos { get; set; }
    }
}
