//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Autoriai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autoriai()
        {
            this.Knygos = new HashSet<Knygo>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Privalomas laukas")]
        [StringLength(50, ErrorMessage = "Vardas negali būti ilgesnis nei 50 simbolių")]
        public string Vardas { get; set; }
        [Required(ErrorMessage = "Privalomas laukas")]
        [StringLength(50, ErrorMessage = "Pavardė negali būti ilgesnė nei 50 simbolių")]
        public string Pavarde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knygo> Knygos { get; set; }
    }
}
