//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_DBEntities : DbContext
    {
        public Project_DBEntities()
            : base("name=Project_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudioKnygo> AudioKnygos { get; set; }
        public virtual DbSet<Autoriai> Autoriais { get; set; }
        public virtual DbSet<Biblioteko> Bibliotekos { get; set; }
        public virtual DbSet<Igarsintojai> Igarsintojais { get; set; }
        public virtual DbSet<Kalbo> Kalbos { get; set; }
        public virtual DbSet<Knygo> Knygos { get; set; }
        public virtual DbSet<Miestai> Miestais { get; set; }
        public virtual DbSet<Skaitytojai> Skaitytojais { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipai> Tipais { get; set; }
        public virtual DbSet<Uzsakymai> Uzsakymais { get; set; }
        public virtual DbSet<UzsakymaiAudioKnygo> UzsakymaiAudioKnygos { get; set; }
        public virtual DbSet<UzsakymaiKnygo> UzsakymaiKnygos { get; set; }
        public virtual DbSet<UzsakymaiZurnalai> UzsakymaiZurnalais { get; set; }
        public virtual DbSet<Zanrai> Zanrais { get; set; }
        public virtual DbSet<Zurnalai> Zurnalais { get; set; }
    }
}
