//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knygo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knygo()
        {
            this.UzsakymaiKnygos = new HashSet<UzsakymaiKnygo>();
        }
    
        public int Id { get; set; }
        public string Pav { get; set; }
        public string Leidykla { get; set; }
        public int Metai { get; set; }
        public Nullable<int> KalbaId { get; set; }
        public Nullable<int> ZanrasId { get; set; }
        public Nullable<int> AutoriusId { get; set; }
    
        public virtual Autoriai Autoriai { get; set; }
        public virtual Kalbo Kalbo { get; set; }
        public virtual Zanrai Zanrai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzsakymaiKnygo> UzsakymaiKnygos { get; set; }
    }
}
