//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Skaitytojai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skaitytojai()
        {
            this.Uzsakymais = new HashSet<Uzsakymai>();
        }
    
        public int Id { get; set; }
        public int kodas { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Gimimo_metai { get; set; }
        public int TelefonoNr { get; set; }
        public string Email { get; set; }
        public Nullable<int> TipasId { get; set; }
        public Nullable<int> BibliotekaId { get; set; }
    
        public virtual Biblioteko Biblioteko { get; set; }
        public virtual Tipai Tipai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakymai> Uzsakymais { get; set; }
    }
}
