//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UzsakymaiKnygo
    {
        public int Id { get; set; }
        public Nullable<int> KnygaId { get; set; }
        public Nullable<int> UzsakymasId { get; set; }
    
        public virtual Knygo Knygo { get; set; }
        public virtual Uzsakymai Uzsakymai { get; set; }
    }
}
