//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzsakymai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzsakymai()
        {
            this.UzsakymaiKnygos = new HashSet<UzsakymaiKnygo>();
            this.UzsakymaiZurnalais = new HashSet<UzsakymaiZurnalai>();
            this.UzsakymaiAudioKnygos = new HashSet<UzsakymaiAudioKnygo>();
        }
    
        public int Id { get; set; }
        public System.DateTime Uzsakymo_Data { get; set; }
        public System.DateTime Grazinimo_Data { get; set; }
        public Nullable<int> SkaitytojasId { get; set; }
        public Nullable<int> BibliotekaId { get; set; }
    
        public virtual Biblioteko Biblioteko { get; set; }
        public virtual Skaitytojai Skaitytojai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzsakymaiKnygo> UzsakymaiKnygos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzsakymaiZurnalai> UzsakymaiZurnalais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UzsakymaiAudioKnygo> UzsakymaiAudioKnygos { get; set; }
    }
}
